const initial = [
  {
    id: "1",
    day: {
      machineName: "Spreading",
      productName: "LM003",
      status: 1,
      activeTime: "1h 15m",
      actProdCount: "2000",
      targetPercent: "96.6",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "21.6",
      reqRate: "20",
    },
    shift: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
    hour: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
  },
  {
    id: "2",
    day: {
      machineName: "Dryer",
      productName: "",
      status: 1,
      activeTime: "0",
      actProdCount: "2106",
      targetPercent: "69",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "19",
      reqRate: "19.6",
    },
    shift: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
    hour: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
  },
  {
    id: "3",
    day: {
      machineName: "VR",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "1969",
      targetPercent: "96",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "16.9",
      reqRate: "19.4",
    },
    shift: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
    hour: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
  },

  {
    id: "4",
    day: {
      machineName: "Vibrator",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "1969",
      targetPercent: "96",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "16.9",
      reqRate: "19.4",
    },
    shift: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
    hour: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
  },
  {
    id: "5",
    day: {
      machineName: "Suiiiiiiii",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "6969",
      targetPercent: "70",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "21.6",
      reqRate: "22",
    },
    shift: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
    hour: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
  },
  {
    id: "6",
    day: {
      machineName: "Messi",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "1969",
      targetPercent: "96",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "16.9",
      reqRate: "19.4",
    },
    shift: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
    hour: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
  },
  {
    id: "7",
    day: {
      machineName: "Neymar",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "6969",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "21.6",
      reqRate: "22",
    },
    shift: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
    hour: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
  },
  {
    id: "8",
    day: {
      machineName: "Dhoni",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "6969",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "21.6",
      reqRate: "22",
    },
    shift: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
    hour: {
      machineName: "",
      productName: "",
      status: 0,
      activeTime: "0",
      actProdCount: "0",
      targetPercent: "0",
      leadOrLag: false,
      leadLagCount: "0",
      actRate: "0",
      reqRate: "0",
    },
  },
];

export default initial;
