const initialDetailState = [
  {
    machineID: "1",
    machineName: "Spreading",
    productName: "LM003",
    lastUpdated: new Date(),
    status: 1,
    activeSince: "",
    hourData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "0",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: "21",
      targetQty: "2000",
      achieveQty: "1900",
      rejectQty: "700",
      rrTakt: "60",
      rrUnit: "50",
      actTakt: "",
      arUnit: "3",
      isLead: true,
      lead: "",
      prodPer: 81,
      availPer: 76,
      qlt: 79,
      oee: 80,
    },
    count: {
      day: {
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
        xAxis: ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: "",
        reqTakt: "",
        actTakt: "",
        xAxis: [
          "04:00",
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
          "20:00",
          "22:00",
        ],
        series: [
          {
            name: "Standard",
            type: "line",
            data: [10, 20, 15, 25, 17, 19, 21, 27, 30, 32],
          },
          {
            name: "Required",
            type: "line",
            data: [15, 21, 17, 27, 19, 20, 24, 29, 31, 33],
          },
          {
            name: "Actual",
            type: "line",
            data: [14, 22, 16, 26, 18, 21, 19, 25, 29, 35],
          },
        ],
      },
    },
    taktTime: {
      target: 0,
      series: [],
      nos: [],
    },
  },
  {
    machineID: "2",
    machineName: "VR",
    productName: "VVLS001",
    lastUpdated: new Date(),
    status: 1,
    activeSince: "",
    hourData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "0",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: "59",
      targetQty: "2000",
      achieveQty: "1800",
      rejectQty: "509",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 79,
      availPer: 81,
      qlt: 70,
      oee: 76,
    },
    count: {
      day: {
        xAxis: ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"],
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: "",
        reqTakt: "",
        actTakt: "",
        xAxis: [
          "04:00",
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
          "20:00",
          "22:00",
        ],
        series: [
          {
            name: "Standard",
            type: "line",
            data: [10, 20, 15, 25, 17, 19, 21, 27, 30, 32],
          },
          {
            name: "Required",
            type: "line",
            data: [15, 21, 17, 27, 19, 20, 24, 29, 31, 33],
          },
          {
            name: "Actual",
            type: "line",
            data: [14, 22, 16, 26, 18, 21, 19, 25, 29, 35],
          },
        ],
      },
    },
    taktTime: {
      target: 0,
      series: [],
      nos: [],
    },
  },
  {
    machineID: "3",
    machineName: "DVD",
    productName: "",
    lastUpdated: new Date(),
    status: 1,
    activeSince: "",
    hourData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "0",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: "49",
      targetQty: "2000",
      achieveQty: "1940",
      rejectQty: "600",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 81,
      availPer: 82,
      qlt: 89,
      oee: 85,
    },
    count: {
      day: {
        xAxis: ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"],
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: "",
        reqTakt: "",
        actTakt: "",
        xAxis: [
          "04:00",
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
          "20:00",
          "22:00",
        ],
        series: [
          {
            name: "Standard",
            type: "line",
            data: [10, 20, 15, 25, 17, 19, 21, 27, 30, 32],
          },
          {
            name: "Required",
            type: "line",
            data: [15, 21, 17, 27, 19, 20, 24, 29, 31, 33],
          },
          {
            name: "Actual",
            type: "line",
            data: [14, 22, 16, 26, 18, 21, 19, 25, 29, 35],
          },
        ],
      },
    },
    taktTime: {
      target: 0,
      series: [],
      nos: [],
    },
  },
  {
    machineID: "4",
    machineName: "Vibrator",
    productName: "",
    lastUpdated: new Date(),
    status: 1,
    activeSince: "",
    hourData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "0",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: "79",
      targetQty: "2300",
      achieveQty: "2200",
      rejectQty: "800",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 65,
      availPer: 67,
      qlt: 71,
      oee: 66,
    },
    count: {
      day: {
        xAxis: ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"],
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: "",
        reqTakt: "",
        actTakt: "",
        xAxis: [
          "04:00",
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
          "20:00",
          "22:00",
        ],
        series: [
          {
            name: "Standard",
            type: "line",
            data: [10, 20, 15, 25, 17, 19, 21, 27, 30, 32],
          },
          {
            name: "Required",
            type: "line",
            data: [15, 21, 17, 27, 19, 20, 24, 29, 31, 33],
          },
          {
            name: "Actual",
            type: "line",
            data: [14, 22, 16, 26, 18, 21, 19, 25, 29, 35],
          },
        ],
      },
    },
    taktTime: {
      target: 0,
      series: [],
      nos: [],
    },
  },
  {
    machineID: "5",
    machineName: "Suiiiiiiii",
    productName: "",
    lastUpdated: new Date(),
    status: 1,
    activeSince: "",
    hourData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "0",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: "69",
      targetQty: "1500",
      achieveQty: "1300",
      rejectQty: "400",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 91,
      availPer: 85,
      qlt: 83,
      oee: 86,
    },
    count: {
      day: {
        xAxis: ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"],
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: "",
        reqTakt: "",
        actTakt: "",
        xAxis: [
          "04:00",
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
          "20:00",
          "22:00",
        ],
        series: [
          {
            name: "Standard",
            type: "line",
            data: [10, 20, 15, 25, 17, 19, 21, 27, 30, 32],
          },
          {
            name: "Required",
            type: "line",
            data: [15, 21, 17, 27, 19, 20, 24, 29, 31, 33],
          },
          {
            name: "Actual",
            type: "line",
            data: [14, 22, 16, 26, 18, 21, 19, 25, 29, 35],
          },
        ],
      },
    },
    taktTime: {
      target: 0,
      series: [],
      nos: [],
    },
  },
  {
    machineID: "6",
    machineName: "Messi",
    productName: "",
    lastUpdated: new Date(),
    status: 0,
    activeSince: "",
    hourData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "0",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: "96",
      targetQty: "3000",
      achieveQty: "2929",
      rejectQty: "710",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 75,
      availPer: 78,
      qlt: 79,
      oee: 77,
    },
    count: {
      day: {
        xAxis: ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"],
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: "",
        reqTakt: "",
        actTakt: "",
        xAxis: [
          "04:00",
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
          "20:00",
          "22:00",
        ],
        series: [
          {
            name: "Standard",
            type: "line",
            data: [10, 20, 15, 25, 17, 19, 21, 27, 30, 32],
          },
          {
            name: "Required",
            type: "line",
            data: [15, 21, 17, 27, 19, 20, 24, 29, 31, 33],
          },
          {
            name: "Actual",
            type: "line",
            data: [14, 22, 16, 26, 18, 21, 19, 25, 29, 35],
          },
        ],
      },
    },
    taktTime: {
      target: 0,
      series: [],
      nos: [],
    },
  },
  {
    machineID: "7",
    machineName: "Neymar",
    productName: "",
    lastUpdated: new Date(),
    status: 0,
    activeSince: "",
    hourData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "0",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: "66",
      targetQty: "1790",
      achieveQty: "1500",
      rejectQty: "300",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 82,
      availPer: 79,
      qlt: 74,
      oee: 78,
    },
    count: {
      day: {
        xAxis: ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"],
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: "",
        reqTakt: "",
        actTakt: "",
        xAxis: [
          "04:00",
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
          "20:00",
          "22:00",
        ],
        series: [
          {
            name: "Standard",
            type: "line",
            data: [10, 20, 15, 25, 17, 19, 21, 27, 30, 32],
          },
          {
            name: "Required",
            type: "line",
            data: [15, 21, 17, 27, 19, 20, 24, 29, 31, 33],
          },
          {
            name: "Actual",
            type: "line",
            data: [14, 22, 16, 26, 18, 21, 19, 25, 29, 35],
          },
        ],
      },
    },
    taktTime: {
      target: 0,
      series: [],
      nos: [],
    },
  },
  {
    machineID: "8",
    machineName: "Dhoni",
    productName: "",
    lastUpdated: new Date(),
    status: 1,
    activeSince: "",
    hourData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "0",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: "",
      targetQty: "",
      achieveQty: "",
      rejectQty: "",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: "60",
      targetQty: "3100",
      achieveQty: "2900",
      rejectQty: "700",
      rrTakt: "",
      rrUnit: "",
      actTakt: "",
      arUnit: "",
      isLead: true,
      lead: "",
      prodPer: 86,
      availPer: 84,
      qlt: 83,
      oee: 85,
    },
    count: {
      day: {
        xAxis: ["06:00", "08:00", "10:00", "12:00", "14:00", "16:00"],
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: "",
        reqTakt: "",
        actTakt: "",
        xAxis: [
          "04:00",
          "06:00",
          "08:00",
          "10:00",
          "12:00",
          "14:00",
          "16:00",
          "18:00",
          "20:00",
          "22:00",
        ],
        series: [
          {
            name: "Standard",
            type: "line",
            data: [10, 20, 15, 25, 17, 19, 21, 27, 30, 32],
          },
          {
            name: "Required",
            type: "line",
            data: [15, 21, 17, 27, 19, 20, 24, 29, 31, 33],
          },
          {
            name: "Actual",
            type: "line",
            data: [14, 22, 16, 26, 18, 21, 19, 25, 29, 35],
          },
        ],
      },
    },
    taktTime: {
      target: 0,
      series: [],
      nos: [],
    },
  },
];

export default initialDetailState;
