const initialOverviewState = [{
    id: '1',
    day: {
      machineName: 'Spreading',
      productName: 'LM003',
      status: 1,
      activeTime: '1h 15m',
      actProdCount: '2000',
      targetPercent: '96.6',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '21.6',
      reqRate: '20',
    },
    shift: {
      machineName: '',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '0',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '0',
      reqRate: '0',
    },
    hour: {
      machineName: '',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '0',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '0',
      reqRate: '0',
    },
  },
  {
    id: '2',
    day: {
      machineName: 'Dryer',
      productName: '',
      status: 1,
      activeTime: '0',
      actProdCount: '2106',
      targetPercent: '69',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '19',
      reqRate: '19.6',
    },
    shift: {
      machineName: '',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '0',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '0',
      reqRate: '0',
    },
    hour: {
      machineName: '',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '0',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '0',
      reqRate: '0',
    },
  },
  {
    id: '3',
    day: {
      machineName: 'VR',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '1969',
      targetPercent: '96',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '16.9',
      reqRate: '19.4',
    },
    shift: {
      machineName: '',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '0',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '0',
      reqRate: '0',
    },
    hour: {
      machineName: '',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '0',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '0',
      reqRate: '0',
    },
  },
  {
    id: '4',
    day: {
      machineName: 'Suiiiiiiii',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '6969',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '21.6',
      reqRate: '22',
    },
    shift: {
      machineName: '',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '0',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '0',
      reqRate: '0',
    },
    hour: {
      machineName: '',
      productName: '',
      status: 0,
      activeTime: '0',
      actProdCount: '0',
      targetPercent: '0',
      leadOrLag: false,
      leadLagCount: '0',
      actRate: '0',
      reqRate: '0',
    },
  }];
  
  const initialDetailState = [{
    machineID: '1',
    machineName: 'Spreading',
    productName: 'LM003',
    lastUpdated: new Date(),
    status: 0,
    activeSince: '',
    hourData: {
      duration: '',
      targetQty: '',
      achieveQty: '',
      rejectQty: '',
      rrTakt: '',
      rrUnit: '',
      actTakt: '',
      arUnit: '',
      isLead: true,
      lead: '0',
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    shiftData: {
      duration: '',
      targetQty: '',
      achieveQty: '',
      rejectQty: '',
      rrTakt: '',
      rrUnit: '',
      actTakt: '',
      arUnit: '',
      isLead: true,
      lead: '',
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    dayData: {
      duration: '',
      targetQty: '',
      achieveQty: '',
      rejectQty: '',
      rrTakt: '',
      rrUnit: '',
      actTakt: '',
      arUnit: '',
      isLead: true,
      lead: '',
      prodPer: 0,
      availPer: 0,
      qlt: 0,
      oee: 0,
    },
    count: {
      day: {
        yAxis: [2300, 2220, 1560, 1230, 980, 1410],
        xAxis: [
        '06:00',
        '08:00',
        '10:00',
        '12:00',
        '14:00',
        '16:00',],
      },
      shift: {
        yAxis: [],
        xAxis: [],
      },
    },
    taktData: {
      day: {
        stdTakt: '',
        reqTakt: '',
        actTakt: '',
        xAxis: [
          '00:00',
          '02:00',
          '04:00',
          '06:00',
          '08:00',
          '10:00',
          '12:00',
          '14:00',
          '16:00',
          '18:00',
          '20:00',
          '22:00',
          '23:59',
        ],
        series: [
            {
              name: 'Standard',
              type: 'line',
              data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            {
              name: 'Required',
              type: 'line',
              data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
            {
              name: 'Actual',
              type: 'line',
              data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            },
          ],
        },
      },
      taktTime: {
        target: 0,
        series: [],
        nos: [],
      },
    },
    {
        machineID: '2',
        machineName: 'VR',
        productName: 'VVLS001',
        lastUpdated: new Date(),
        status: 1,
        activeSince: '',
        hourData: {
          duration: '',
          targetQty: '',
          achieveQty: '',
          rejectQty: '',
          rrTakt: '',
          rrUnit: '',
          actTakt: '',
          arUnit: '',
          isLead: true,
          lead: '0',
          prodPer: 0,
          availPer: 0,
          qlt: 0,
          oee: 0,
        },
        shiftData: {
          duration: '',
          targetQty: '',
          achieveQty: '',
          rejectQty: '',
          rrTakt: '',
          rrUnit: '',
          actTakt: '',
          arUnit: '',
          isLead: true,
          lead: '',
          prodPer: 0,
          availPer: 0,
          qlt: 0,
          oee: 0,
        },
        dayData: {
          duration: '',
          targetQty: '2000',
          achieveQty: '2109',
          rejectQty: '109',
          rrTakt: '',
          rrUnit: '',
          actTakt: '',
          arUnit: '',
          isLead: true,
          lead: '',
          prodPer: 0,
          availPer: 0,
          qlt: 0,
          oee: 0,
        },
        count: {
          day: {
            yAxis: [],
            xAxis: [],
          },
          shift: {
            yAxis: [],
            xAxis: [],
          },
        },
        taktData: {
          day: {
            stdTakt: '',
            reqTakt: '',
            actTakt: '',
            xAxis: [
              '00:00',
              '02:00',
              '04:00',
              '06:00',
              '08:00',
              '10:00',
              '12:00',
              '14:00',
              '16:00',
              '18:00',
              '20:00',
              '22:00',
              '23:59',
            ],
            series: [
                {
                  name: 'Standard',
                  type: 'line',
                  data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                },
                {
                  name: 'Required',
                  type: 'line',
                  data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                },
                {
                  name: 'Actual',
                  type: 'line',
                  data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                },
              ],
            },
          },
          taktTime: {
            target: 0,
            series: [],
            nos: [],
          },
        },
        {
            machineID: '3',
            machineName: 'DVD',
            productName: '',
            lastUpdated: new Date(),
            status: 0,
            activeSince: '',
            hourData: {
              duration: '',
              targetQty: '',
              achieveQty: '',
              rejectQty: '',
              rrTakt: '',
              rrUnit: '',
              actTakt: '',
              arUnit: '',
              isLead: true,
              lead: '0',
              prodPer: 0,
              availPer: 0,
              qlt: 0,
              oee: 0,
            },
            shiftData: {
              duration: '',
              targetQty: '',
              achieveQty: '',
              rejectQty: '',
              rrTakt: '',
              rrUnit: '',
              actTakt: '',
              arUnit: '',
              isLead: true,
              lead: '',
              prodPer: 0,
              availPer: 0,
              qlt: 0,
              oee: 0,
            },
            dayData: {
              duration: '',
              targetQty: '',
              achieveQty: '',
              rejectQty: '',
              rrTakt: '',
              rrUnit: '',
              actTakt: '',
              arUnit: '',
              isLead: true,
              lead: '',
              prodPer: 0,
              availPer: 0,
              qlt: 0,
              oee: 0,
            },
            count: {
              day: {
                xAxis: [
                  '06:00',
                  '08:00',
                  '10:00',
                  '12:00',
                  '14:00',
                  '16:00',],
                yAxis: [2300, 2220, 1560, 1230, 980, 1410],

              },
              shift: {
                yAxis: [],
                xAxis: [],
              },
            },
            taktData: {
              day: {
                stdTakt: '',
                reqTakt: '',
                actTakt: '',
                xAxis: [
                  '00:00',
                  '02:00',
                  '04:00',
                  '06:00',
                  '08:00',
                  '10:00',
                  '12:00',
                  '14:00',
                  '16:00',
                  '18:00',
                  '20:00',
                  '22:00',
                  '23:59',
                ],
                series: [
                    {
                      name: 'Standard',
                      type: 'line',
                      data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    },
                    {
                      name: 'Required',
                      type: 'line',
                      data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    },
                    {
                      name: 'Actual',
                      type: 'line',
                      data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    },
                  ],
                },
              },
              taktTime: {
                target: 0,
                series: [],
                nos: [],
              },
            }];


    const initialMetadataState = {
        day: {
          d: '',
          e: '',
          r: '',
        },
        shift: {
          d: '',
          e: '',
          r: '',
        },
        hour: {
          d: '',
          e: '',
          r: '',
        },
      };
      

export default initialDetailState;
export {initialOverviewState,initialMetadataState};
  